# Generated by Django 4.2.7 on 2023-11-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('director', models.CharField(max_length=150, verbose_name='Director')),
                ('release_date', models.DateField(null=True, verbose_name='Fecha de lanzamiento')),
            ],
        ),
    ]
