# Generated by Django 4.2.7 on 2023-11-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='banner',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada'),
        ),
    ]
